Only run 1 phpunit during pre-commit
The rest will be handled by GitHub Actions

diff --git a/dev/git-hooks/pre-commit b/dev/git-hooks/pre-commit
--- a/dev/git-hooks/pre-commit
+++ b/dev/git-hooks/pre-commit
@@ -60,32 +60,23 @@ function exit_reset_colors() {
     exit 1
 }
 
-# Must run them consecutively to prevent conflicts.
-function php_units() {
-	php_unit "phpunit ${LEGACY_PHP_VERSION}" 'phpunit-legacy.xml.dist'
-    php_unit "phpunit ${LEGACY_PHP_VERSION}" "phpunit-legacy.xml.dist --bootstrap=${PHPUNIT_DIR}/bootstrap-legacy-single.php"
-    php_unit "phpunit ${LEGACY_PHP_VERSION}" "phpunit-legacy.xml.dist --bootstrap=${PHPUNIT_DIR}/bootstrap-single.php"
-	php_unit "phpunit ${LEGACY_PHP_VERSION}" "phpunit-legacy.xml.dist --bootstrap=${PHPUNIT_DIR}/bootstrap.php"
-	php_unit "phpunit ${PHP_VERSION}" 'phpunit.xml.dist'
-    php_unit "phpunit ${PHP_VERSION}" "phpunit.xml.dist --bootstrap=${PHPUNIT_DIR}/bootstrap-single.php"
-}
-
 function php_unit() {
-        if [[ ! -f ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml ]] && [[ ! -f ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml.dist ]]; then
-            echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml or ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml.dist not found!"
-            exit_reset_colors
-        fi
-        echo "${YELLOW}[pre-commit]${BLUE} Running ${1^^} ${2}... ${WHITE}"
-        OUTPUT=$(${1} --configuration ${PROJECT}/${PHPUNIT_DIR}/${2})
-        if [[ $? != 0 ]]; then
-            echo
-            echo "${BLUE}${1^^} ${2} Failed! Fix the error before commit!"
-            echo "${RED}$OUTPUT"
-            exit_reset_colors
-        fi
-        echo "${YELLOW}[pre-commit]${GREEN} ${1^^} ${2} Tests Passed!${RESET_COLOR}"
+    if [[ ! -f ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml ]] && [[ ! -f ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml.dist ]]; then
+        echo "${YELLOW}[pre-commit]${RED} ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml or ${PROJECT}/${PHPUNIT_DIR}/phpunit.xml.dist not found!"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${BLUE} Running PHP Unit... ${WHITE}"
+    cd "${PROJECT}/${PHPUNIT_DIR}" || exit
+    OUTPUT=$(${PHPUNIT})
+    if [[ $? != 0 ]]; then
+        echo
+        echo "${BLUE}PHP Unit Failed! Fix the error before commit!"
+        echo "${RED}$OUTPUT"
+        exit_reset_colors
+    fi
+    echo "${YELLOW}[pre-commit]${GREEN} PHP Unit Tests Passed!${RESET_COLOR}"
 }
-php_units &
+php_unit &
 
 function php_lint() {
     if [[ "$PHP_FILES" ]]; then
